"""AIP versions and approvals (Phase 7, insert-only + immutability trigger)

Revision ID: 3522ec8dfd5d
Revises: 989ef563481c
Create Date: 2026-07-22 19:12:27.788358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3522ec8dfd5d'
down_revision: Union[str, Sequence[str], None] = '989ef563481c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_identity_profile_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aip_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_from_token', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aip_id'], ['artist_identity_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aip_id', 'version_number', name='uq_aip_version_number')
    )
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('context', sa.String(length=16), server_default=sa.text("'individual'"), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['artist_identity_profile_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Persistence-level immutability (REQ-014, ADR-005, D7-3): block
    # UPDATE on approved version and approval rows for every role,
    # including the application role. DELETE is intentionally NOT blocked
    # so BR-015 artist-aggregate deletion can cascade; the domain layer
    # exposes no single-version delete path.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION mc_reject_update() RETURNS trigger AS $$
        BEGIN
          RAISE EXCEPTION
            'immutable row: UPDATE on % is not permitted (REQ-014)',
            TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER aip_versions_no_update
          BEFORE UPDATE ON artist_identity_profile_versions
          FOR EACH ROW EXECUTE FUNCTION mc_reject_update();
        """
    )
    op.execute(
        """
        CREATE TRIGGER approvals_no_update
          BEFORE UPDATE ON approvals
          FOR EACH ROW EXECUTE FUNCTION mc_reject_update();
        """
    )
    # The autogenerated drops of ix_audit_entity and uq_workspaces_singleton
    # were removed by hand: both are expression/manual indexes autogenerate
    # cannot see in the models (uq_workspaces_singleton is the B2 singleton
    # guarantee). See migration 989ef563481c for the same caution.


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS approvals_no_update ON approvals")
    op.execute(
        "DROP TRIGGER IF EXISTS aip_versions_no_update "
        "ON artist_identity_profile_versions"
    )
    op.execute("DROP FUNCTION IF EXISTS mc_reject_update()")
    op.drop_table('approvals')
    op.drop_table('artist_identity_profile_versions')
