"""User password_hash credential (Phase 8, D8-3)

Revision ID: 687c205cf24f
Revises: 3522ec8dfd5d
Create Date: 2026-07-23 08:03:07.293952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687c205cf24f'
down_revision: Union[str, Sequence[str], None] = '3522ec8dfd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the credential column only. The autogenerated drops of
    # ix_audit_entity and uq_workspaces_singleton are spurious: both are
    # expression/manual indexes autogenerate cannot see in the models
    # (uq_workspaces_singleton is the B2 workspace-singleton guarantee).
    # Recorded caution, D6-1 migration note.
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'password_hash')
