"""AIP sections JSONB document (DEC-02, D6-1)

Revision ID: 989ef563481c
Revises: c5b7e3a9f214
Create Date: 2026-07-21 17:03:51.939271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '989ef563481c'
down_revision: Union[str, Sequence[str], None] = 'c5b7e3a9f214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add the sections JSONB document. The autogenerated drops of
    ix_audit_entity and uq_workspaces_singleton were removed by hand:
    both are expression/manual indexes autogenerate cannot see in the
    models (uq_workspaces_singleton is the B2 singleton guarantee)."""
    op.add_column(
        'artist_identity_profiles',
        sa.Column(
            'sections',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Remove the sections column only."""
    op.drop_column('artist_identity_profiles', 'sections')
